[package]
name = "traildb"
version = "0.1.0"
authors = ["Jay Kickliter <jay@kickliter.com>"]
build = "build.rs"

[dependencies]
libc = "0.2.11"
uuid = {version = "0.2.2", features = ["v4"] }

[build-dependencies]
bindgen = "0.17.0"

[dev-dependencies]
chrono = "0.2.22"