[package]
name = "traildb"
version = "0.1.0"
authors = ["Jay Kickliter <jay@kickliter.com>"]
build = "build.rs"

[dependencies]
libc = "^0.2.0"

[build-dependencies]
bindgen = "^0.17.0"

[dev-dependencies]
uuid = {version = "0.2.2", features = ["v4"] }
